name: SimpleDye
version: '${project.version}'
main: adhdmc.simpledye.SimpleDye
api-version: 1.19
authors: [ Peashooter101, Rhythmic ]
description: Simple Dye for Leather and other dyable items.
permissions:
  simpledye.simple:
    description: Allow simple dyeing of leather armor.
    usage: /<command> simple [color]
    default: op
  simpledye.rgb:
    description: Allow rgb dyeing of leather armor using hex colors.
    usage: /<command> rgb [#RRGGBB|RRGGBB]
    default: op
  simpledye.*:
    description: Wildcard permission.
    usage: /<command>
    default: op
commands:
  sd:
    description: Simple Dyeing Command
    aliases:
      - simpledye
    permission-message: You do not have permission.
    usage: /<command> [simple|rgb]